### ISSUE TITLE
Screen problems in portrait mode (large display, Android 12)

### ISSUE THREAD

**Issue by dnlombard** [connectbot/connectbot#1168]
## Bug description
The display is incorrect (missing output, &etc.) for certain operations when the tablet is oriented in Portrait mode.

- Edit host only shows partial info in portrait mode but full info (including correct scrolling) in landscape mode.
- Connect forces portrait mode (shows 159x68 resolution at screen bottom). There's no apparent ability to interact with the host once connected. Typing emits a keyclick sound but there's not apparent response desptire any input. Server's /var/log/secure shows the SSH connection was established. Only option is to disconnect via ConnectBot menu.

## Steps to reproduce

1. Start app
2. Edit host in portrai mode, screen is as shown in Screenshot_Connectbot-EditHost-Portrait.jpg.
3. Edit host in landscape mode, screen is as shown in Screenshot_Connectbot-EditHost-Landscape.jpg
4. Connect to host forces screen to portrait mode, will not allow landscape mode. Screen is as shown in Screenshot_Connectbot-Connected.jpg. 

## Expected behavior

1. Edit host works in portrait and landscape mode
2. Connection works

## Screenshots
![Screenshot_Connectbot-EditHost-Portrait](https://user-images.githubusercontent.com/9848989/189283096-de3e75e1-47e9-45f8-978e-5a98e350ac92.jpg)
![Screenshot_Connectbot-EditHost-Landscape](https://user-images.githubusercontent.com/9848989/189284265-dc11cf66-5d03-4454-a707-a68cd8e77fec.jpg)
![Screenshot_Connectbot-Connected](https://user-images.githubusercontent.com/9848989/189283125-ede0d13e-2beb-48c8-8e7f-a5e3b349b650.jpg)

## Android device
Device: Samsung Tab S8+ 5G
OS: Android 12 SP1A.2100812.016.X808USQU2AVE4
ConnectBot Version: 1.9.8

## Server information
OS: Fedora 36
SSH Software and Version: OpenSSH 8.8p2

## Additional context
None

**Comment by dnlombard** [comment]
The screen resolution of the device is 2800 x 1752

**Comment by 4r1-60ld** [comment]
I was just about to report what looks like the same issue with my OnePlus 7 Pro with the latest crDroid. I am happy ti writeup all the information like @dnlombard has done, but other than de device being different, it's pretty much the same.
Thank you.

**Comment by AreYouLoco** [comment]
Please change issue title to "Portrait display problem on android 12". I experience the same problem it was working fine on android 11

**Comment by AreYouLoco** [comment]
I just checked and downgrading to 1.9.5-oss gets rid of the issue. Could someone experiencing the same problem verify?

**Comment by 4r1-60ld** [comment]
> I just checked and downgrading to 1.9.5-oss gets rid of the issue. Could someone experiencing the same problem verify?

Verified. Downgrading to 1.9.5 gets rid of the issue.

**Comment by much-doge** [comment]
> Please change issue title to "Portrait display problem on android 12". I experience the same problem it was working fine on android 11

The issue also appears even on android 10, samsung device (my resolution is 2220x1080)

**Comment by n00b12345** [comment]
Please fix this. I'm also facing the issue. Only downgrading works.

**Comment by n00b12345** [comment]
> I just checked and downgrading to 1.9.5-oss gets rid of the issue. Could someone experiencing the same problem verify?

Yes, downgrading fixes the issue.

**Comment by dnlombard** [comment]
Any info on a fix?

The latest playstore package, 20230208, is still unusable on large-screen device. Samsung Galaxy S22 phone works fine; Samsung Galaxy Tab S8+ doesn't.

**Comment by arturwolf** [comment]
I could fix it in a private Image.

I changed in fragment_host_editor.xml

<ScrollView
...
from
android:fillViewport="true"
to
android:fillViewport="false"

With this change screen is now ok.

**Comment by kruton** [comment]
I think this is most likely fixed in the latest v1.10 beta (i.e., v1.9.3-156 or later) which has a complete rewrite of the UI.

**Comment by puskyer** [comment]
I know that this is closed but the problem is back on version  "ConnectBot-git-v1.9.13-364-g4b321519-oss.apk" i am using a Galaxy TAB S4 SM-T830

**Comment by kruton** [comment]
Please open a new issue and include screenshots. Providing more detail even if you think it's irrelevant is helpful.
