### ISSUE TITLE
Migration failed with the latest version

### ISSUE THREAD

**Issue by Dehumanizer77** [connectbot/connectbot#1632]
## Bug description
After installing latest version I am getting "Migration failed, An error occured during database migration: Duplicate host nicknames found" and I am unable to use the application since it does not let me do anything, there is only "retry" button, but retrying returns the same screen again.

## Steps to reproduce

1. open the aplication
2. the error shows up

## Android device

 - Device: Google Pixel 8 Pro
 - OS: Android 16 (stock rom)
 - ConnectBot Version: 1.9.13-46

## Additional context

The error probably started appearing 2 versions behind, because I wanted to use connectbot, I got this error, then I went to google play to check if there isn't any update and there was an update available, so I have updated and the error stayed. But I have used connectbot 1 or 2 days back without problems so it has to be some recent change that caused this.

**Comment by kruton** [comment]
v1.9.13-47 should fix this. Thanks for the bug report!

**Comment by ferdnyc** [comment]
Whoops, I opened #1675 before finding this, but it looks like the issue is back.

**Comment by Dehumanizer77** [comment]
I have just updated to 1.9.13.108 and I don't experience the issue.

**Comment by ferdnyc** [comment]
@Dehumanizer77 I guess one question is, what version were you coming _from_?

It's possible (read: very likely) I haven't opened ConnectBot in at least a few weeks (maybe as long as 2-3 months) before yesterday, so the schema for the DB being migrated _from_ could be older in my case.

**Comment by ferdnyc** [comment]
(Also, as my screenshot on #1675 shows, it's not _exactly_ the same issue. The issue in your report had to do with duplicate host nicknames. The error in my case was something nebulous regarding foreign key constraints.)

**Comment by Dehumanizer77** [comment]
Yes, that is certainly possible if you skipped some versions. I am using and updating connectbot often.
