### ISSUE TITLE
Toolbar is missing back button on Pubkeys / Colors / Settings / Help screen

### ISSUE THREAD

**Issue by wp9015362** [connectbot/connectbot#173]
Hello,

when being in the terminal, the toolbar has a back button, as you can see in the following screenshot (highlighted in red circle):

![Image](https://cloud.githubusercontent.com/assets/7558360/9573621/c603120c-4fbe-11e5-81df-56f0d2aec4ba.png)

But the back button is missing from the toolbar when being on the Pubkeys / Colors / Settings / Help screen.

Could you please fix it and add the back button to the toolbar when being on the Pubkeys / Colors / Settings / Help screen?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
PS:

The back button is also missing from the toolbar on the Help - Hints / Help - PhysicalKeyboard / Help - ScreenGestures / Help - VirtualKeyboard screen.

Regards

**Comment by kruton** [comment]
Fixed this with #197

**Comment by wp9015362** [comment]
@kruton :

Looks like this issue is not fixed, see:

https://github.com/connectbot/connectbot/issues/224

As you can see on those screenshots, the back button is still missing.

Regards
